### ISSUE TITLE
Not compatible with browser Wasm (via wasm-bindgen)

### ISSUE THREAD

**Issue by RReverser** [jedisct1/rust-benchmark-simple#1]
The crate description says

> (WASI, but also in-browser)

but it uses `std::time` which is not supported on wasm32-unknown-unknown and will panic at runtime.

It should use the `time` crate instead, which has a dedicated `wasm-bindgen` feature to use the browser API instead of stdlib.

**Comment by jedisct1** [comment]
It uses the `precision` crate, that is [supposed to call the JavaScript `performance.now()` function](https://github.com/jedisct1/rust-precision/blob/f8032315b861844b0b063bda93eb0638598bc9e2/src/cpucounter.rs#L47-L65).

I don't see any place where `std::time` is used, expect for the `std::time::Duration` type.

Is importing a type enough to make it panic? That would be surprising (OTOH, code from the standard library that compiles, but is expected to be unusable is counterintuitive as well).

**Comment by RReverser** [comment]
Hmm sorry, maybe the panic was elsewhere. I rushed to check the code, saw `std::time` and jumped to conclusions without digging deeper. I'll recheck in the evening.

**Comment by jedisct1** [comment]
Yeah, I wasn't able to reproduce that on a simple example using `benchmark-simple`.
Unfortunately the stack trace when compiling Rust to WebAssembly is completely useless.

**Comment by RReverser** [comment]
Ah, apologies then. I'll close the issue.
